name: Deploy (self-hosted, static)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Release & switch symlink
        run: |
          set -euo pipefail
          APP_DIR="/home/ec2-user/apps"
          REL_DIR="${APP_DIR}/releases"
          REPO_NAME="${GITHUB_REPOSITORY##*/}"
          SHA="${GITHUB_SHA}"

          mkdir -p "${REL_DIR}"

          # ✅ 깔끔한 아카이브: .git 제외, 파일 변경 경고 없음
          TAR="app-${SHA}.tar.gz"
          git archive --format=tar.gz --output="${TAR}" "${SHA}"

          mkdir -p "${REL_DIR}/${REPO_NAME}-${SHA}"
          tar -xzf "${TAR}" -C "${REL_DIR}/${REPO_NAME}-${SHA}"

          ln -sfn "${REL_DIR}/${REPO_NAME}-${SHA}" "${APP_DIR}/current"

          sudo chmod 755 /home/ec2-user /home/ec2-user/apps /home/ec2-user/apps/current
          sudo find /home/ec2-user/apps/current -type d -exec chmod 755 {} \;
          sudo find /home/ec2-user/apps/current -type f -exec chmod 644 {} \;

      - name: Reload nginx
        run: sudo nginx -t && sudo systemctl reload nginx
