name: Deploy to EC2 (tarball)

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: ${{ secrets.EC2_PORT || 22 }}
          timeout: 60s
          script: |
            set -euo pipefail

            APP_DIR="/home/ec2-user/apps"
            REL_DIR="${APP_DIR}/releases"
            SHA="${{ github.sha }}"
            REPO="${{ github.repository }}"      # owner/repo
            REPO_NAME="${REPO##*/}"              # repo
            TARBALL_URL="https://codeload.github.com/${REPO}/tar.gz/${SHA}"

            mkdir -p "${REL_DIR}"
            cd "${REL_DIR}"

            echo "Downloading tarball..."
            curl -L "${TARBALL_URL}" -o "app-${SHA}.tar.gz"

            echo "Extracting..."
            tar -xzf "app-${SHA}.tar.gz"

            # 🔧 GitHub tarball 최상위 폴더명은 <repo>-<sha>
            NEW_DIR="${REPO_NAME}-${SHA}"

            cd "${REL_DIR}/${NEW_DIR}"

            if [ -f package.json ]; then
              npm ci || npm install
              npm run build || true
            fi

            ln -sfn "${REL_DIR}/${NEW_DIR}" "${APP_DIR}/current"

            if pm2 describe myapp >/dev/null 2>&1; then
              pm2 reload myapp
            else
              pm2 start "${APP_DIR}/current/server.js" --name myapp
              pm2 save
            fi

            sudo nginx -t && sudo systemctl reload nginx || true
